services:

  init:
    container_name: civilizations_init
    image: oven/bun:latest
    user: bun
    working_dir: /home/bun/app
    volumes:
      - .:/home/bun/app:cached
    command: bun run prisma:init

  front:
    profiles: ["app"]
    container_name: civilizations_front
    image: oven/bun:latest
    user: bun
    extra_hosts:
      - "localhost:172.17.0.1"
    ports:
      - "8080:8080"
    working_dir: /home/bun/app/apps/front
    volumes:
      - .:/home/bun/app:cached
    command: bun dev
    networks:
      - civilizations

  back:
    profiles: ["app"]
    container_name: civilizations_back
    image: oven/bun:latest
    user: bun
    ports:
      - "${DOCKER_BACK_EXTERNAL_PORT}:3000"
    working_dir: /home/bun/app/apps/back
    volumes:
      - .:/home/bun/app:cached
    command: bun dev
    networks:
      - civilizations
    depends_on:
      - mongo

  mongo:
    profiles: ["app"]
    container_name: civilizations_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - civilizations
    volumes:
      - mongo:/data/db

networks:
  civilizations:

volumes:
  mongo:
