[build]
command = "bun run build"
publish = "apps/front/build"

[context.production.environment]
BACK_URL = "http://home.darthoit.eu:26064"

[[redirects]]
from = "/*"
to = "/.netlify/functions/handler"
status = 200
force = true
