[build]
command = "bun run build"
publish = "build"

[context.production.environment]
PUBLIC_BACK_URL = "https://civilization-api.darthoit.eu"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
